kind: Deployment
apiVersion: apps/v1
metadata:
  name: mall-order
  namespace: gulimall
  labels:
    app: mall-order
#  annotations:
#    deployment.kubernetes.io/revision: '1'
#    kubesphere.io/alias-name: mall-order
#    kubesphere.io/maxSurgePod: '2'
#    kubesphere.io/minAvailablePod: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-order
  template:
    metadata:
      labels:
        app: mall-order
    spec:
      containers:
        - name: mall-order
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  #      dnsPolicy: ClusterFirst
  #      serviceAccountName: default
  #      serviceAccount: default
  #      securityContext: {}
  #      affinity: {}
  #      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: mall-order
  namespace: gulimall
  labels:
    app: mall-order
#  annotations:
#    kubesphere.io/alias-name: mall-order
#    kubesphere.io/serviceType: statelessservice
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20011
  selector:
    app: mall-order
  type: NodePort
  sessionAffinity: None
#  externalTrafficPolicy: Cluster
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 10800
